### PR TITLE
Fixing the typos

### LINKED ISSUE #32: Fixing the typos
Hey @AryaChakraborty,
I found several typos. 
Fox ex:- src/llms/azurechat.py line 62 `AI assitant` should be `AI assistant`

Assign this to me, I would like to fix them. Kindly add the GSSOC'24 label and level.

### PR DESCRIPTION
**Pull request by NIKHIL0VERMA**
Fixies the typos
Closes #32

### CODE REVIEW

**Comment by AryaChakraborty** [comment]
please do not change the variables that are used in the code... Rest looks file to me.

**Comment by AryaChakraborty** [comment]
I believe you didn't revert the changes in few files... especially the azurechat caught my eye

**Comment by NIKHIL0VERMA** [comment]
Okay okay got it. 
I think grammatically correcting prompts will break the system 💁.

Things that caught ☝️ my eye are:

- At line 53 changing the `AI assitant` with `AI assistant` makes it not eligible for merge 🙅
- But in line 62 `AI assitant` changed to  `AI assistant` as mentioned in original issue #32 as an example of typos found by me. Fixed with PR #35 by someone else is merged 👌

I think things are going so high level that I can't comprehend.
Thanks for pointing out my mistake 😅
I will revert my damages in azurechat and ollama.

Hope for the best of your project.
Not looking to contribute again 😊😃😃

**Comment by AryaChakraborty** [comment]
@NIKHIL0VERMA please read the code of conduct from the next time.

**Comment by NIKHIL0VERMA** [comment]
@AryaChakraborty **Plz consider knowing about the program before submitting you project. **

I read the code of conduct and asked you politely, but what you did was not acceptable. 

GSSOC is beginners friendly and you're expecting different things. Your response is not very welcoming for complete beginners. I was following GSSOC guidelines.

If you just stated that you can't accept the typo fixing PR just like any other PA, anyone could accept it.

If raising voice for myself is violating code of conduct I will do it and I think anyone will.

What wrong did I stated. Nothing, I just pointed out the facts that are true, didn't it that you merged the prompt fixing PR and rejected my PR bcz of same??

**Pull request closed without merging**
