### PR TITLE
Dockerized & requirements.txt fixed #58 #15

### LINKED ISSUE #58: Conflict in requirements.txt file
You ask for pydantic==2.7.1,
but beyondllm 0.2.0 depends on pydantic<2 and >=1.10.5.
So, there is a conflict that needs to be resolved.

### PR DESCRIPTION
**Pull request by DebasisX**
This is the final commit after resolving the conflicts in requirements.txt and have also added the Dockerfile with environment variables in the .env file which is loaded in the app.py.

### CODE REVIEW

**Comment by AryaChakraborty** [comment]
@DebasisX I think we already have .env.example to mock the environment variables

additionally, I don't see any command that would export the variables in the environment. Let me know if i missed something.

**Comment by DebasisX** [comment]
I just added a better comment to the mock .env.example file.

As for the Dockerfile,
The .env is copied into the container and when the app.py is launched the python code can access the .env variables so there's no need to export. 
I also checked out the app.py it loads .env by default so I didn't had to add that.

**Comment by AryaChakraborty** [comment]
@sbk2k1 can you please review the commits?

**Review by DebasisX — COMMENTED** [review]
Looks good.

**Review by sbk2k1 — APPROVED** [review]

**Comment by DebasisX** [comment]
@AryaChakraborty So there's an issue, regarding the label as my GSSoC points aren't updated.

The label should be marked as level3
i.e. there shouldn't be any space between label and the corresponding numbers.
Kindly help me by reassigning the labels.
Thank you.

**Pull request merged**
