### PR TITLE
Create Dockerfile

### PR DESCRIPTION
**Pull request by sanmarg**
In Correspondence to the issue #15

### CODE REVIEW

**Comment by sbk2k1** [comment]
@sanmarg could you please look into getting the env vars from a .env file? If so

- get vars from an .env file
- add it to .gitignore
- make a .env.example file mocking the required vars

**Comment by sanmarg** [comment]
Can you please ellaborate

**Comment by sbk2k1** [comment]
@sanmarg instead of using <environment_variables> placeholder in the dockerfile to be replaced during build time. Instead, I would like you to look into getting those variables from a .env file.

**Review by gratusrichard — CHANGES_REQUESTED** [review]
As mentioned in the previous comments, having ENV variables would be easier to reproduce. Also, provide a .env.example file for the format of env.

**Pull request closed without merging**
